-- +goose Up
-- Auto-generated by the server on startup and via a daily background job.
CREATE TABLE IF NOT EXISTS recurring_payment_occurrences (
    id INTEGER NOT NULL,
    recurring_payment_id INTEGER NOT NULL,
    due_date DATE NOT NULL,
    amount INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- +goose Down
DROP TABLE IF EXISTS recurring_payment_occurrences;
