package db

import (
	"context"
	"embed"
	"fmt"
	"io/fs"
	"log/slog"

	"github.com/pressly/goose/v3"
)

//go:embed migrations/*.sql
var embedMigrations embed.FS

func init() {
	// Silence goose's default logger; portal uses slog.
	goose.SetLogger(goose.NopLogger())
}

// MigrateDB applies all pending up-migrations to the provided database.
// It is idempotent: already-applied migrations are skipped.
// Goose records applied migrations in the goose_db_version tracking table.
//
// This is intended for use in tests where a live Nexus control endpoint is
// not available (e.g. an in-process DuckDB instance), as well as for
// single-tenant migration during registration.
func MigrateDB(db *PortalDB) error {
	slog.Info("running database migrations via db connection")

	// Pre-create the goose version table with DuckLake-compatible DDL.
	// Goose's DialectPostgres uses GENERATED BY DEFAULT AS IDENTITY which
	// DuckLake does not support.  We create the table first; goose then skips
	// its own CREATE TABLE IF NOT EXISTS.
	if err := createGooseVersionTable(db); err != nil {
		return fmt.Errorf("failed to initialize goose version table: %w", err)
	}

	provider, err := newProvider(db)
	if err != nil {
		return err
	}

	results, err := provider.Up(context.Background())
	if err != nil {
		return fmt.Errorf("database migration failed: %w", err)
	}

	for _, r := range results {
		slog.Info("applied migration", "version", r.Source.Version, "duration", r.Duration)
	}

	slog.Info("database migrations complete")
	return nil
}

// RollbackDB rolls back the last n applied migrations in reverse order.
// Pass n <= 0 to roll back all applied migrations.
func RollbackDB(db *PortalDB, n int) error {
	provider, err := newProvider(db)
	if err != nil {
		return err
	}

	if n <= 0 {
		// Roll back everything down to version 0.
		results, err := provider.DownTo(context.Background(), 0)
		if err != nil {
			return fmt.Errorf("database rollback failed: %w", err)
		}
		for _, r := range results {
			slog.Info("rolled back migration", "version", r.Source.Version, "duration", r.Duration)
		}
		slog.Info("rollback complete", "rolled_back", len(results))
		return nil
	}

	// Roll back n steps one at a time.
	for i := 0; i < n; i++ {
		result, err := provider.Down(context.Background())
		if err != nil {
			return fmt.Errorf("database rollback step %d failed: %w", i+1, err)
		}
		if result != nil {
			slog.Info("rolled back migration", "version", result.Source.Version, "duration", result.Duration)
		}
	}

	slog.Info("rollback complete", "rolled_back", n)
	return nil
}

// MigrateTenant runs schema migrations for a single tenant database.
// Occurrence generation is handled separately by the platform service.
func MigrateTenant(tenantDB *PortalDB, tenantID string) error {
	slog.Info("migrating tenant schema", "tenant_id", tenantID)

	if err := MigrateDB(tenantDB); err != nil {
		return fmt.Errorf("migration failed for tenant %s: %w", tenantID, err)
	}

	slog.Info("migration complete for tenant", "tenant_id", tenantID)
	return nil
}

// newProvider builds a goose provider backed by the embedded SQL migration
// files and the raw *sql.DB (bypassing the lake. schema prefix rewrite used
// by PortalDB for application queries).
func newProvider(db *PortalDB) (*goose.Provider, error) {
	migFS, err := fs.Sub(embedMigrations, "migrations")
	if err != nil {
		return nil, fmt.Errorf("failed to create migration filesystem: %w", err)
	}

	provider, err := goose.NewProvider(goose.DialectPostgres, db.DB, migFS)
	if err != nil {
		return nil, fmt.Errorf("failed to create goose provider: %w", err)
	}
	return provider, nil
}

// createGooseVersionTable pre-creates the goose_db_version tracking table with
// DuckLake-compatible DDL before goose.NewProvider runs.  Goose normally
// creates this table itself using "id integer PRIMARY KEY GENERATED BY DEFAULT
// AS IDENTITY" (PostgreSQL-specific); DuckLake does not support PRIMARY KEY or
// GENERATED, but will auto-increment a plain INTEGER id column.  Because goose
// uses CREATE TABLE IF NOT EXISTS, it will skip creation when the table already
// exists, so this must be called first.
func createGooseVersionTable(db *PortalDB) error {
	const createSQL = `CREATE TABLE IF NOT EXISTS goose_db_version (
		id INTEGER,
		version_id BIGINT NOT NULL,
		is_applied BOOLEAN NOT NULL,
		tstamp TIMESTAMP
	);`
	if _, err := db.DB.Exec(createSQL); err != nil {
		return fmt.Errorf("failed to create goose_db_version table: %w", err)
	}

	// Seed the zero-version baseline row if it does not already exist.
	// Goose normally inserts this row during its own table creation; since we
	// created the table above, goose skips that step and we must seed it here.
	var count int
	if err := db.QueryRow("SELECT COUNT(1) FROM goose_db_version WHERE version_id = 0").Scan(&count); err != nil {
		return fmt.Errorf("failed to check goose zero version: %w", err)
	}
	if count == 0 {
		if _, err := db.Exec("INSERT INTO goose_db_version (version_id, is_applied) VALUES (0, true)"); err != nil {
			return fmt.Errorf("failed to seed goose zero version: %w", err)
		}
	}

	return nil
}
