package db

import (
	"fmt"
	"log/slog"
)

// MigrateDB runs all DDL statements directly against the provided database.
// This is intended for use in tests where a live Nexus control endpoint is
// not available (e.g. an in-process DuckDB instance).
func MigrateDB(db *PortalDB) error {
	slog.Info("running database migrations via db connection")

	for _, stmt := range migrations {
		if _, err := db.Exec(stmt); err != nil {
			return fmt.Errorf("migration failed: %w\nstatement: %s", err, stmt)
		}
	}

	slog.Info("database migrations complete")
	return nil
}

// MigrateAndGenerateTenant runs migrations and occurrence generation for a single tenant.
// This function accepts a tenant-specific database connection and:
//  1. Runs all DDL statements to create the portal schema for this tenant
//  2. Generates any pending recurring payment occurrences
//
// This is the recommended approach for both:
//   - New tenant registration (pass the new tenant's DB connection)
//   - Batch processing all tenants (call once per tenant in a loop)
// MigrateTenant runs schema migrations for a single tenant database.
// Occurrence generation is handled separately by the platform service.
func MigrateTenant(tenantDB *PortalDB, tenantID string) error {
	slog.Info("migrating tenant schema", "tenant_id", tenantID)

	if err := MigrateDB(tenantDB); err != nil {
		return fmt.Errorf("migration failed for tenant %s: %w", tenantID, err)
	}

	slog.Info("migration complete for tenant", "tenant_id", tenantID)
	return nil
}

var migrations = []string{
	// Tables: auto-incrementing IDs are handled via 'SERIAL PRIMARY KEY' (Nexus/DuckLake recommendation)
	// Accounts: bank, cash, credit card
	`CREATE TABLE IF NOT EXISTS accounts (
		id INTEGER NOT NULL,
		name TEXT NOT NULL,
		type TEXT NOT NULL,
		opening_balance INTEGER NOT NULL DEFAULT 0,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL
	)`,

	// Contacts: vendors and customers
	`CREATE TABLE IF NOT EXISTS contacts (
		id INTEGER NOT NULL,
		name TEXT NOT NULL,
		type TEXT NOT NULL,
		email TEXT,
		phone TEXT,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL
	)`,

	// Bills: payable to vendors
	`CREATE TABLE IF NOT EXISTS bills (
		id INTEGER NOT NULL,
		contact_id INTEGER,
		bill_number TEXT,
		issue_date DATE,
		due_date DATE,
		amount INTEGER NOT NULL DEFAULT 0,
		status TEXT NOT NULL DEFAULT 'draft',
		file_url TEXT,
		notes TEXT,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL
	)`,

	// Invoices: receivable from customers
	`CREATE TABLE IF NOT EXISTS invoices (
		id INTEGER NOT NULL,
		contact_id INTEGER,
		invoice_number TEXT,
		issue_date DATE,
		due_date DATE,
		amount INTEGER NOT NULL DEFAULT 0,
		status TEXT NOT NULL DEFAULT 'draft',
		file_url TEXT,
		notes TEXT,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL
	)`,

	// Bank transactions: income, expense, transfer
	`CREATE TABLE IF NOT EXISTS transactions (
		id INTEGER NOT NULL,
		account_id INTEGER NOT NULL,
		type TEXT NOT NULL,
		amount INTEGER NOT NULL DEFAULT 0,
		transaction_date DATE,
		description TEXT,
		reference TEXT,
		transfer_account_id INTEGER,
		contact_id INTEGER,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL
	)`,

	// Junction table: many-to-many transaction <-> bill/invoice/payout/recurring_payment_occurrence.
	// No CHECK constraint on document_type — valid types are enforced by the application layer.
	`CREATE TABLE IF NOT EXISTS transaction_documents (
		id INTEGER NOT NULL,
		transaction_id INTEGER NOT NULL,
		document_type TEXT NOT NULL,
		document_id INTEGER NOT NULL,
		amount INTEGER NOT NULL,
		created_at TIMESTAMP NOT NULL
	)`,

	// Payouts from Swiggy/Zomato/Swiggy-Dineout
	`CREATE TABLE IF NOT EXISTS payouts (
		id INTEGER NOT NULL,
		outlet_name TEXT NOT NULL,
		platform TEXT NOT NULL,
		period_start DATE,
		period_end DATE,
		settlement_date TEXT,
		total_orders INTEGER NOT NULL DEFAULT 0,
		gross_sales_amt INTEGER NOT NULL DEFAULT 0,
		restaurant_discount_amt INTEGER NOT NULL DEFAULT 0,
		platform_commission_amt INTEGER NOT NULL DEFAULT 0,
		taxes_tcs_tds_amt INTEGER NOT NULL DEFAULT 0,
		marketing_ads_amt INTEGER NOT NULL DEFAULT 0,
		final_payout_amt INTEGER NOT NULL DEFAULT 0,
		utr_number TEXT,
		created_at TIMESTAMP NOT NULL
	)`,

	// Recurring payments: scheduled income or expense
	`CREATE TABLE IF NOT EXISTS recurring_payments (
		id INTEGER NOT NULL,
		name TEXT NOT NULL,
		type TEXT NOT NULL,
		amount INTEGER NOT NULL,
		account_id INTEGER NOT NULL,
		contact_id INTEGER,
		frequency TEXT NOT NULL,
		interval INTEGER NOT NULL DEFAULT 1,
		start_date DATE NOT NULL,
		end_date DATE,
		next_due_date DATE,
		last_generated_date DATE,
		status TEXT NOT NULL DEFAULT 'active',
		description TEXT,
		reference TEXT,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL
	)`,

	// Recurring payment occurrences: one row per scheduled occurrence of a recurring payment.
	// Auto-generated by the server on startup and via a daily background job.
	`CREATE TABLE IF NOT EXISTS recurring_payment_occurrences (
		id INTEGER NOT NULL,
		recurring_payment_id INTEGER NOT NULL,
		due_date DATE NOT NULL,
		amount INTEGER NOT NULL,
		status TEXT NOT NULL DEFAULT 'pending',
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL
	)`,

	// Bill items: individual line items for a bill
	`CREATE TABLE IF NOT EXISTS bill_items (
		id INTEGER NOT NULL,
		bill_id INTEGER NOT NULL,
		description TEXT NOT NULL,
		quantity DOUBLE NOT NULL DEFAULT 1,
		unit TEXT,
		unit_price INTEGER NOT NULL DEFAULT 0,
		amount INTEGER NOT NULL DEFAULT 0,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL
	)`,

	// Invoice items: individual line items for an invoice
	`CREATE TABLE IF NOT EXISTS invoice_items (
		id INTEGER NOT NULL,
		invoice_id INTEGER NOT NULL,
		description TEXT NOT NULL,
		quantity DOUBLE NOT NULL DEFAULT 1,
		unit TEXT,
		unit_price INTEGER NOT NULL DEFAULT 0,
		amount INTEGER NOT NULL DEFAULT 0,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL
	)`,
}
