package db

// store_duckdb.go provides a goose Store implementation backed by DuckDB-compatible
// SQL. DuckDB does not support the PostgreSQL `GENERATED BY DEFAULT AS IDENTITY`
// syntax used by goose's built-in postgres dialect, so this store is used for
// DuckDB databases (e.g. in tests).

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io/fs"

	"github.com/pressly/goose/v3"
	"github.com/pressly/goose/v3/database"
)

// duckdbStore implements database.Store using DuckDB-compatible SQL.
type duckdbStore struct {
	tablename string
	seqname   string
}

var _ database.Store = (*duckdbStore)(nil)

func newDuckDBStore(tablename string) *duckdbStore {
	return &duckdbStore{
		tablename: tablename,
		seqname:   tablename + "_seq",
	}
}

func (s *duckdbStore) Tablename() string { return s.tablename }

func (s *duckdbStore) CreateVersionTable(ctx context.Context, db database.DBTxConn) error {
	// DuckDB uses sequences for auto-increment, not GENERATED BY DEFAULT AS IDENTITY.
	createSeq := fmt.Sprintf(`CREATE SEQUENCE IF NOT EXISTS %s START 1`, s.seqname)
	if _, err := db.ExecContext(ctx, createSeq); err != nil {
		return fmt.Errorf("failed to create sequence %q: %w", s.seqname, err)
	}
	createTbl := fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s (
		id      INTEGER PRIMARY KEY DEFAULT nextval('%s'),
		version_id BIGINT  NOT NULL,
		is_applied BOOLEAN NOT NULL,
		tstamp     TIMESTAMP DEFAULT now()
	)`, s.tablename, s.seqname)
	if _, err := db.ExecContext(ctx, createTbl); err != nil {
		return fmt.Errorf("failed to create version table %q: %w", s.tablename, err)
	}
	// Seed version 0 (goose convention). Use INSERT OR IGNORE equivalent so that
	// CreateVersionTable is idempotent when the table already exists but is empty.
	_, err := db.ExecContext(ctx,
		fmt.Sprintf(
			`INSERT INTO %s (version_id, is_applied)
			 SELECT $1, $2
			 WHERE NOT EXISTS (SELECT 1 FROM %s WHERE version_id = $1)`,
			s.tablename, s.tablename,
		),
		0, true,
	)
	if err != nil {
		return fmt.Errorf("failed to seed initial version: %w", err)
	}
	return nil
}

func (s *duckdbStore) Insert(ctx context.Context, db database.DBTxConn, req database.InsertRequest) error {
	q := fmt.Sprintf(`INSERT INTO %s (version_id, is_applied) VALUES ($1, $2)`, s.tablename)
	if _, err := db.ExecContext(ctx, q, req.Version, true); err != nil {
		return fmt.Errorf("failed to insert version %d: %w", req.Version, err)
	}
	return nil
}

func (s *duckdbStore) Delete(ctx context.Context, db database.DBTxConn, version int64) error {
	q := fmt.Sprintf(`DELETE FROM %s WHERE version_id = $1`, s.tablename)
	if _, err := db.ExecContext(ctx, q, version); err != nil {
		return fmt.Errorf("failed to delete version %d: %w", version, err)
	}
	return nil
}

func (s *duckdbStore) GetMigration(
	ctx context.Context,
	db database.DBTxConn,
	version int64,
) (*database.GetMigrationResult, error) {
	q := fmt.Sprintf(
		`SELECT tstamp, is_applied FROM %s WHERE version_id = $1 ORDER BY tstamp DESC LIMIT 1`,
		s.tablename,
	)
	var result database.GetMigrationResult
	err := db.QueryRowContext(ctx, q, version).Scan(&result.Timestamp, &result.IsApplied)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, fmt.Errorf("%w: %d", database.ErrVersionNotFound, version)
		}
		return nil, fmt.Errorf("failed to get migration %d: %w", version, err)
	}
	return &result, nil
}

func (s *duckdbStore) GetLatestVersion(ctx context.Context, db database.DBTxConn) (int64, error) {
	q := fmt.Sprintf(`SELECT MAX(version_id) FROM %s`, s.tablename)
	var version sql.NullInt64
	if err := db.QueryRowContext(ctx, q).Scan(&version); err != nil {
		return -1, fmt.Errorf("failed to get latest version: %w", err)
	}
	if !version.Valid {
		return -1, fmt.Errorf("%w: no migrations", database.ErrVersionNotFound)
	}
	return version.Int64, nil
}

func (s *duckdbStore) ListMigrations(
	ctx context.Context,
	db database.DBTxConn,
) ([]*database.ListMigrationsResult, error) {
	q := fmt.Sprintf(`SELECT version_id, is_applied FROM %s ORDER BY id DESC`, s.tablename)
	rows, err := db.QueryContext(ctx, q)
	if err != nil {
		return nil, fmt.Errorf("failed to list migrations: %w", err)
	}
	defer rows.Close()
	var results []*database.ListMigrationsResult
	for rows.Next() {
		var r database.ListMigrationsResult
		if err := rows.Scan(&r.Version, &r.IsApplied); err != nil {
			return nil, fmt.Errorf("failed to scan migration row: %w", err)
		}
		results = append(results, &r)
	}
	return results, rows.Err()
}

// newTestProvider returns a goose provider configured for DuckDB databases.
// Production code uses newProvider (postgres dialect); use this for DuckDB
// (e.g. in tests or when a DuckDB database is used directly).
func newTestProvider(db *PortalDB) (*goose.Provider, error) {
	migFS, err := fs.Sub(embedMigrations, "migrations")
	if err != nil {
		return nil, fmt.Errorf("failed to create migration filesystem: %w", err)
	}
	store := newDuckDBStore("goose_db_version")
	provider, err := goose.NewProvider("", db.DB, migFS, goose.WithStore(store))
	if err != nil {
		return nil, fmt.Errorf("failed to create goose provider: %w", err)
	}
	return provider, nil
}

// MigrateTestDB applies all pending migrations using a DuckDB-compatible goose
// provider. Use this in tests where a DuckDB database is used directly instead
// of going through the Nexus gateway with the PostgreSQL wire protocol.
//
// It creates the 'lake' schema in the DuckDB database and sets it as the default
// search path so that table references using the 'lake.' prefix (added by
// PortalDB.rebind) are resolved correctly.
func MigrateTestDB(db *PortalDB) error {
	// Create the lake schema and set it as the default so that application tables
	// are created there and match the lake. prefix that PortalDB.rebind adds.
	if _, err := db.DB.Exec("CREATE SCHEMA IF NOT EXISTS lake"); err != nil {
		return fmt.Errorf("failed to create lake schema: %w", err)
	}
	if _, err := db.DB.Exec("SET search_path = lake"); err != nil {
		return fmt.Errorf("failed to set search_path: %w", err)
	}

	provider, err := newTestProvider(db)
	if err != nil {
		return err
	}
	if _, err := provider.Up(context.Background()); err != nil {
		return fmt.Errorf("database migration failed: %w", err)
	}
	return nil
}
