package models

// RecurringPayment represents a scheduled recurring payment (income or expense).
type RecurringPayment struct {
	ID                int       `json:"id"`
	Name              string    `json:"name"`
	Type              string    `json:"type"` // income, expense
	Amount            Money     `json:"amount"`
	AccountID         int       `json:"account_id"`
	ContactID         *int      `json:"contact_id"`
	Frequency         string    `json:"frequency"` // daily, weekly, monthly, quarterly, yearly
	Interval          int       `json:"interval"`  // every N frequencies (e.g. 2 = every 2 months)
	StartDate         string    `json:"start_date"`
	EndDate           *string   `json:"end_date"`
	NextDueDate       *string   `json:"next_due_date"`
	LastGeneratedDate *string   `json:"last_generated_date"`
	Status            string    `json:"status"` // active, paused, cancelled, completed
	Description       *string   `json:"description"`
	Reference         *string   `json:"reference"`
	CreatedAt         Timestamp `json:"created_at"`
	UpdatedAt         Timestamp `json:"updated_at"`
	// Computed fields
	AccountName *string `json:"account_name,omitempty"`
	ContactName *string `json:"contact_name,omitempty"`
}

// RecurringPaymentOccurrence represents a single scheduled instance of a recurring payment.
// Occurrences are auto-generated by the server for each due date up to today.
type RecurringPaymentOccurrence struct {
	ID                 int       `json:"id"`
	RecurringPaymentID int       `json:"recurring_payment_id"`
	DueDate            string    `json:"due_date"`
	Amount             Money     `json:"amount"`
	Status             string    `json:"status"` // pending, paid, skipped
	CreatedAt          Timestamp `json:"created_at"`
	UpdatedAt          Timestamp `json:"updated_at"`
	// Computed fields
	Allocated   Money   `json:"allocated"`
	Unallocated Money   `json:"unallocated"`
	PaymentName *string `json:"payment_name,omitempty"`
}

// RecurringPaymentInput is used for creating/updating recurring payments.
type RecurringPaymentInput struct {
	Name              string  `json:"name"`
	Type              string  `json:"type"`
	Amount            Money   `json:"amount"`
	AccountID         int     `json:"account_id"`
	ContactID         *int    `json:"contact_id"`
	Frequency         string  `json:"frequency"`
	Interval          int     `json:"interval"`
	StartDate         string  `json:"start_date"`
	EndDate           *string `json:"end_date"`
	NextDueDate       *string `json:"next_due_date"`
	LastGeneratedDate *string `json:"last_generated_date"`
	Status            string  `json:"status"`
	Description       *string `json:"description"`
	Reference         *string `json:"reference"`
}

func (r *RecurringPaymentInput) Validate() string {
	if r.Name == "" {
		return "name is required"
	}
	switch r.Type {
	case "income", "expense":
	default:
		return "type must be one of: income, expense"
	}
	if r.Amount <= 0 {
		return "amount must be positive"
	}
	if r.AccountID <= 0 {
		return "account_id is required"
	}
	switch r.Frequency {
	case "daily", "weekly", "monthly", "quarterly", "yearly":
	default:
		return "frequency must be one of: daily, weekly, monthly, quarterly, yearly"
	}
	if r.Interval <= 0 {
		return "interval must be greater than 0"
	}
	if r.StartDate == "" {
		return "start_date is required"
	}
	if err := NormalizeDate(&r.StartDate); err != nil {
		return "start_date: " + err.Error()
	}
	if err := NormalizeDate(r.EndDate); err != nil {
		return "end_date: " + err.Error()
	}
	if err := NormalizeDate(r.NextDueDate); err != nil {
		return "next_due_date: " + err.Error()
	}
	if err := NormalizeDate(r.LastGeneratedDate); err != nil {
		return "last_generated_date: " + err.Error()
	}
	switch r.Status {
	case "", "active", "paused", "cancelled", "completed":
	default:
		return "status must be one of: active, paused, cancelled, completed"
	}
	if r.Status == "" {
		r.Status = "active"
	}
	return ""
}
